use anyhow::{anyhow, Context, Result};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

use super::compression::Compression;

/// Session metadata persisted to `<session>/metadata.env`. Stored in a
/// `KEY=value` format that's both bash-sourceable (matching the original
/// scripts) and trivial to parse from Rust.
#[derive(Debug, Clone)]
pub struct Metadata {
    pub input_deb: PathBuf,
    pub session_dir: PathBuf,
    pub data_compress: Compression,
    pub control_compress: Compression,
    pub created_at: String,
    pub package_name: Option<String>,
    pub package_version: Option<String>,
    pub package_arch: Option<String>,
}

impl Metadata {
    pub fn load(path: &Path) -> Result<Self> {
        let text =
            fs::read_to_string(path).with_context(|| format!("Reading {}", path.display()))?;
        let kv = parse_env(&text);
        let get = |key: &str| -> Result<String> {
            kv.get(key)
                .cloned()
                .ok_or_else(|| anyhow!("metadata.env missing required key: {}", key))
        };
        Ok(Metadata {
            input_deb: PathBuf::from(get("INPUT_DEB")?),
            session_dir: PathBuf::from(get("SESSION_DIR")?),
            data_compress: Compression::from_keyword(&get("DATA_COMPRESS")?)?,
            control_compress: Compression::from_keyword(&get("CONTROL_COMPRESS")?)?,
            created_at: get("CREATED_AT")?,
            package_name: kv.get("PACKAGE_NAME").cloned(),
            package_version: kv.get("PACKAGE_VERSION").cloned(),
            package_arch: kv.get("PACKAGE_ARCH").cloned(),
        })
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let mut out = String::new();
        out.push_str("# Debian Package Session Metadata\n");
        out.push_str("# Generated by deb-toolkit session open\n\n");
        push_kv(&mut out, "INPUT_DEB", &self.input_deb.to_string_lossy());
        push_kv(&mut out, "SESSION_DIR", &self.session_dir.to_string_lossy());
        push_kv(&mut out, "DATA_COMPRESS", self.data_compress.as_keyword());
        push_kv(
            &mut out,
            "CONTROL_COMPRESS",
            self.control_compress.as_keyword(),
        );
        push_kv(&mut out, "CREATED_AT", &self.created_at);
        out.push_str("\n# Original package info\n");
        push_kv(
            &mut out,
            "PACKAGE_NAME",
            self.package_name.as_deref().unwrap_or("unknown"),
        );
        push_kv(
            &mut out,
            "PACKAGE_VERSION",
            self.package_version.as_deref().unwrap_or("unknown"),
        );
        push_kv(
            &mut out,
            "PACKAGE_ARCH",
            self.package_arch.as_deref().unwrap_or("unknown"),
        );
        fs::write(path, out).with_context(|| format!("Writing {}", path.display()))?;
        Ok(())
    }
}

/// Parse a `KEY=value` file. Supports single-quoted, double-quoted, and
/// bare values, plus bash-style `KEY=$'...'` escape sequences (limited to
/// `\n`, `\t`, `\\`, `\'`).
fn parse_env(text: &str) -> HashMap<String, String> {
    let mut out = HashMap::new();
    for raw in text.lines() {
        let line = raw.trim_start();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((k, v)) = line.split_once('=') else {
            continue;
        };
        let key = k.trim().to_string();
        let value = unquote(v.trim());
        out.insert(key, value);
    }
    out
}

fn unquote(s: &str) -> String {
    let bytes = s.as_bytes();
    if bytes.len() >= 2 {
        if bytes[0] == b'\'' && bytes[bytes.len() - 1] == b'\'' {
            return s[1..s.len() - 1].to_string();
        }
        if bytes[0] == b'"' && bytes[bytes.len() - 1] == b'"' {
            return s[1..s.len() - 1].to_string();
        }
    }
    // Bash's printf %q sometimes emits `$'...'` for strings with metachars.
    if s.starts_with("$'") && s.ends_with('\'') && s.len() >= 3 {
        let inner = &s[2..s.len() - 1];
        let mut out = String::with_capacity(inner.len());
        let mut chars = inner.chars();
        while let Some(c) = chars.next() {
            if c == '\\' {
                match chars.next() {
                    Some('n') => out.push('\n'),
                    Some('t') => out.push('\t'),
                    Some('\\') => out.push('\\'),
                    Some('\'') => out.push('\''),
                    Some(other) => out.push(other),
                    None => {}
                }
            } else {
                out.push(c);
            }
        }
        return out;
    }
    s.to_string()
}

/// Write a `KEY=value` pair, single-quoting `value` when it contains
/// whitespace or metacharacters. This mirrors `printf '%q'`'s common case
/// closely enough for the values we persist.
fn push_kv(out: &mut String, key: &str, value: &str) {
    let needs_quote = value.is_empty()
        || value
            .chars()
            .any(|c| c.is_whitespace() || matches!(c, '\'' | '"' | '$' | '`' | '\\' | '#'));
    if needs_quote {
        // Use single quotes; escape any embedded `'` as `'\''`.
        out.push_str(key);
        out.push_str("='");
        out.push_str(&value.replace('\'', "'\\''"));
        out.push_str("'\n");
    } else {
        out.push_str(key);
        out.push('=');
        out.push_str(value);
        out.push('\n');
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn roundtrip_metadata() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("metadata.env");
        let meta = Metadata {
            input_deb: PathBuf::from("/tmp/foo bar.deb"),
            session_dir: PathBuf::from("/tmp/sess"),
            data_compress: Compression::Gzip,
            control_compress: Compression::Xz,
            created_at: "2026-05-17T00:00:00Z".to_string(),
            package_name: Some("mina-daemon".to_string()),
            package_version: Some("1.0.0".to_string()),
            package_arch: Some("amd64".to_string()),
        };
        meta.save(&path).unwrap();
        let back = Metadata::load(&path).unwrap();
        assert_eq!(back.input_deb, meta.input_deb);
        assert_eq!(back.data_compress, meta.data_compress);
        assert_eq!(back.control_compress, meta.control_compress);
        assert_eq!(back.package_name, meta.package_name);
        assert_eq!(back.package_version, meta.package_version);
    }

    #[test]
    fn parse_env_handles_quotes() {
        let text = "FOO=bar\nBAZ='hello world'\nQUX=\"a b c\"\n# comment\nEMPTY=''\n";
        let kv = parse_env(text);
        assert_eq!(kv["FOO"], "bar");
        assert_eq!(kv["BAZ"], "hello world");
        assert_eq!(kv["QUX"], "a b c");
        assert_eq!(kv["EMPTY"], "");
    }
}
